jwt:
    secret: 'phND9slneUVAwGPI9Iakqhf0IfmyXV9lXRdIVrHEDE12Hf2a6Kt704fpznm3oiQy33K2w6ZbfYANK0'

server:
    port: 8080
#  error:
#    whitelabel:
#      enabled: false

logging:
    level:
        br.com.alura.alurapic: DEBUG
        org.springframework.web: ERROR
        org.springframework.security: ERROR
        org.hibernate: ERROR


spring:
    datasource:
        url: jdbc:mysql://localhost:3306/alurapic
        username: root
    #        password: password
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect